# 1. Datasource config
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/uber_ola
spring.datasource.username: root
spring.datasource.password: hariom

## 2. Hibernate config
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

app-config:
  perKmPrice: 100
  tempCabLockTime: 30


